### PR TITLE
Update Linux Plugin for Kernel 3.0

### PR DESCRIPTION
**Pull request by affix**
Updated the Kernel plugin to work with 3.0 Kernels

### CODE REVIEW

**Comment by nanotube** [comment]
Hi Affix,
Looks reasonable, I presume you have tested it to work adequately?

**Comment by affix** [comment]
yes I tested it and it works perfectly

**Comment by nanotube** [comment]
sounds good, thank you :)

**Comment by affix** [comment]
I will lookout for more plugins to add might even write a few :D

**Pull request merged**
